org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
systemProp.gradle.user.home=C:/gradle_cache
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
